#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load any custom after code
if [ -d $HOME/.zsh/ ]; then
  if [ "$(ls -A $HOME/.zsh/)" ]; then
    for config_file ($HOME/.zsh/*.zsh) source $config_file
  fi
fi